name: Simple flake8

on:
  push:
    branches: [master]

jobs:
  Test-Windows-Server:
    name: Test Windows Server
    runs-on: windows-latest
    steps:
      - name: Install Wix v4
        shell: powershell
        run: dotnet tool install --global wix

      - name: Test Wix Version
        shell: powershell
        run: wix --version
