name: Simple flake8

on: workflow_dispatch

jobs:
  Flake8-test:
    name: Install & run flake8 test
    runs-on: ubuntu-latest
    steps:
      - name: Install dib
        shell: bash
        run: sudo apt update && sudo apt install flake8

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: naestia/randzone
          path: .
          
      - name: Run flake8
        shell: bash
        run: flake8 -v

